version: '2.1'

services:
    db_colossus:
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=amcpherson
        - POSTGRES_PASSWORD=shahlab
        - POSTGRES_DB=colossus_dev
      healthcheck:
        test: ["CMD", "curl", "-f", "http://db_colossus:5432"]
        interval: 30s
        timeout: 10s
        retries: 2

    django:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: colossus
      image: docker_colossus
      stdin_open: true
      tty: true
      command: ["python", "manage.py", "runserver", "8001"]
      volumes:
        - .:/colossus
      ports:
        - "8001:8001"
      depends_on:
        - db_colossus

